import Sidebar from "@/components/ads/Sidebar";
import { Questions } from "@/components/question";
import RequireAuth from "@/utils/RequireAuth";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Questions",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <RequireAuth>
      <div className="flex flex-col md:flex-row">
        <Sidebar />
        <div className="container px-5 mx-auto max-w-6xl">
          <Questions />
        </div>
        <Sidebar />
      </div>
    </RequireAuth>
  );
}
