import Questions from "@/components/Questions";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Questions",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div className="p-5 mx-auto max-w-7xl">
      <Questions />
    </div>
  );
}
