import Sidebar from "@/components/ads/Sidebar";
import { Chapters } from "@/components/chapter";
import { Questions } from "@/components/question";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Questions",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div className="flex flex-col md:flex-row max-w-[1450px] mx-auto gap-4">
      <div className="md:w-[25%]">
        <Chapters />
      </div>
      <div className="container px-5 mx-auto md:w-[75%]">
        <Questions />
      </div>
      <Sidebar />
    </div>
  );
}
