import ChapterAds from "@/components/ads/ChapterAds";
import { Chapters } from "@/components/chapter";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Chapters",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div className="container p-5 mx-auto max-w-6xl">
      <Chapters />
      <div className="mt-10">
        <ChapterAds />
      </div>
    </div>
  );
}
