import { Chapters } from "@/components/chapter";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Chapters",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div className="container p-5 mx-auto max-w-7xl">
      <Chapters />
    </div>
  );
}
