import type { Metadata } from "next";
import "./globals.css";
import CustomThemeProvider from "@/utils/ThemeProvider";
import { Toaster } from "react-hot-toast";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Study Here",
  description: "Generated by create next app",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f3f4f6" },
    { media: "(prefers-color-scheme: dark)", color: "#020617" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="theme-color"
          content="#f3f4f6"
          media="(prefers-color-scheme: light)"
        />
        <meta
          name="theme-color"
          content="#020617"
          media="(prefers-color-scheme: dark)"
        />
      </head>
      <body className="bg-gray-100 dark:bg-slate-950 text-slate-950 dark:text-gray-100">
        <CustomThemeProvider>
          <Header />
          {children}
          <Toaster position="bottom-center" reverseOrder={true} />
        </CustomThemeProvider>
      </body>
    </html>
  );
}
