import type { Metadata } from "next";
import "./globals.css";
import CustomThemeProvider from "@/utils/ThemeProvider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Ioe Exam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 dark:bg-slate-950 text-slate-950 dark:text-gray-100">
        <CustomThemeProvider>
          {children}
          <Toaster />
        </CustomThemeProvider>
      </body>
    </html>
  );
}
