import type { Metadata } from "next";
import "./globals.css";
import CustomThemeProvider from "@/utils/ThemeProvider";

export const metadata: Metadata = {
  title: "Ioe Exam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CustomThemeProvider>
        <body className="bg-gray-100 dark:bg-slate-950 text-slate-950 dark:text-gray-100">
          {children}
        </body>
      </CustomThemeProvider>
    </html>
  );
}
