import { Questions } from "@/components/question";
import RequireAuth from "@/utils/RequireAuth";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Questions",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <RequireAuth>
      <div className="p-5 mx-auto max-w-7xl">
        <Questions />
      </div>
    </RequireAuth>
  );
}
