import { Footer } from "@/components/footer";
import MainLayout from "@/components/layout/MainLayout";
import { PrivacyPolicy } from "@/components/privacy";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Privacy Policy | LearnHere",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <MainLayout>
      <PrivacyPolicy />
    </MainLayout>
  );
}
