import { Chapters } from "@/components/chapter";
import MainLayout from "@/components/layout/MainLayout";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Chapters",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <MainLayout>
        <div className="mx-auto max-w-[1400px] px-4 container flex min-[900px]:flex-row flex-col-reverse gap-4 relative">
          {/* Main content */}
          <div className="w-full">
            <Chapters />
          </div>
        </div>
      </MainLayout>
    </>
  );
}
