import { Chapters } from "@/components/v2/chapter";
import MainLayout from "@/components/layout/MainLayout";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Chapters",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <MainLayout>
      <Chapters />
    </MainLayout>
  );
}
